name: action-validation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing Action
        uses: ishitachawla/action-repo-validation@releases/1
        with:
          GITHUB_TOKEN: ${{secrets.PAT_TOKEN}}
          
