name: "build"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Testing action
      uses: ishitachawla/Check-Requirements@master
      with:
        GITHUB_TOKEN: ${{ secrets.PAT_Token }}
