name: "build"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Testing action
      uses: ishitachawla/action-repo-validation@releases/3
      with:
        GITHUB_TOKEN: ${{ secrets.PAT_Token }}
        repositories: "Check-Requirements"
