name: "build"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: testing action
      id: hello
      uses: ishitachawla/Final@check
      with:
        repository: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.PAT_Token }}
    - name: Get the output 
      run: echo ${{secrets.PAT_Token}}
